"""Session check-in API — the input layer of the hot/cold tier mechanism.

When a user opens a tool's UI, the dashboard POSTs `/api/sessions` with the
service name + their user_id. The orchestrator inserts a row in
platform.service_sessions (which auto-generates a UUID token). While the
user has the tab open, the dashboard sends `POST /api/sessions/{token}/checkin`
every ~60s — the orchestrator refreshes `last_heartbeat_at`. When the user
closes the tab, DELETE sets `closed_at`.

The reconciler reads service_sessions every 30s and stops services with
no recent heartbeats AND no pin.

User identity: until M3.5 wires up real session cookies, every session
defaults to the seeded system user (config.DEFAULT_USER_ID = 1) so the
NOT NULL FK on service_sessions.user_id is satisfied. The dashboard at
M3.5 will pass the actual authenticated user id.
"""

from __future__ import annotations

from uuid import UUID

from fastapi import APIRouter, HTTPException, Response
from pydantic import BaseModel, Field

from .. import audit, config, db, docker_ops

router = APIRouter(prefix="/api/sessions", tags=["sessions"])


class SessionOpenRequest(BaseModel):
    service: str = Field(..., description="Service name from SERVICE_CATALOGUE")
    user_id: int | None = Field(None, description="Optional — defaults to system user")
    auto_start: bool = Field(
        True,
        description=(
            "If true, the orchestrator starts the service in the background "
            "when the session opens. Set False for sessions where you just "
            "want to record interest without spinning anything up."
        ),
    )


@router.post("", status_code=201)
async def open_session(req: SessionOpenRequest) -> dict[str, object]:
    """Open a session against a service. Auto-starts the service by default.

    Returns the session token the client must use for subsequent checkins
    and the eventual DELETE. The token is generated by postgres via the
    DEFAULT gen_random_uuid() on service_sessions.token.
    """
    if req.service not in config.SERVICE_CATALOGUE:
        raise HTTPException(404, f"unknown service: {req.service}")

    user_id = req.user_id if req.user_id is not None else config.DEFAULT_USER_ID

    # RETURNING gives us the auto-generated token from the schema's
    # DEFAULT clause — no need to generate it on the client side.
    row = await db.fetchrow(
        """
        INSERT INTO platform.service_sessions
            (service_name, user_id)
        VALUES ($1, $2)
        RETURNING token
        """,
        req.service, user_id,
    )
    token = row["token"]

    await audit.write(
        "session_opened",
        service_name=req.service, user_id=user_id,
        details={"token": str(token), "auto_start": req.auto_start},
    )

    started = False
    if req.auto_start:
        meta = config.SERVICE_CATALOGUE[req.service]
        if meta.get("managed", False):
            result = await docker_ops.start_service(req.service)
            started = result.ok
            await audit.write(
                "session_autostart" if result.ok else "session_autostart_failed",
                service_name=req.service, user_id=user_id,
                details={"returncode": result.returncode, "stderr": result.short_stderr},
            )
        else:
            # Service is in the catalogue but not yet "managed" (no compose
            # snippet — M4 work). Record the session anyway; nothing to start.
            await audit.write(
                "session_autostart_skipped_unmanaged",
                service_name=req.service, user_id=user_id,
            )

    return {"token": str(token), "service": req.service, "started": started}


@router.post("/{token}/checkin")
async def checkin(token: UUID) -> dict[str, object]:
    """Refresh last_heartbeat_at for an open session. Idempotent.

    No-op if the session doesn't exist or has been closed — the reconciler
    only counts sessions where closed_at IS NULL, so a closed session
    wouldn't extend a service's life even if we did update it.
    """
    row = await db.fetchrow(
        """
        UPDATE platform.service_sessions
        SET last_heartbeat_at = now()
        WHERE token = $1 AND closed_at IS NULL
        RETURNING token
        """,
        token,
    )
    return {"ok": True, "matched": row is not None}


@router.delete("/{token}")
async def close_session(token: UUID) -> Response:
    """Close a session. We don't physically delete the row — setting closed_at
    leaves history visible to the M3 dashboard's audit view AND to M5's
    evaluation queries (which count session durations to estimate usage).

    Returns HTTP 204 via an explicit Response object. See the same comment
    in pinning.py — the decorator's status_code=204 can't be used directly
    in FastAPI 0.115 because of a route-registration assertion.
    """
    row = await db.fetchrow(
        """
        UPDATE platform.service_sessions
        SET closed_at = now()
        WHERE token = $1 AND closed_at IS NULL
        RETURNING service_name, user_id
        """,
        token,
    )
    if row is not None:
        await audit.write(
            "session_closed",
            service_name=row["service_name"], user_id=row["user_id"],
            details={"token": str(token)},
        )
    return Response(status_code=204)
