"""Session check-in API — the input layer of the hot/cold tier mechanism.

When a user opens a tool's UI, Streamlit POSTs `/api/sessions` with the
service name + their user_id. The orchestrator inserts (or updates) a row
in platform.service_sessions. While the user has the tab open, Streamlit
sends `POST /api/sessions/{token}/checkin` every ~60s — the orchestrator
refreshes `last_seen_at`. When the user closes the tab, DELETE removes
the row.

The reconciler reads service_sessions every 30s and stops services that
have no active session AND aren't pinned AND have been up past the
start-grace window.

Session tokens are opaque UUIDs generated by Streamlit (or the test
client). We use them rather than the database primary key so a session
can be uniquely addressed by its caller without needing a server
round-trip to learn the ID.
"""

from __future__ import annotations

from uuid import UUID, uuid4

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from .. import audit, config, db, docker_ops

router = APIRouter(prefix="/api/sessions", tags=["sessions"])


class SessionOpenRequest(BaseModel):
    service: str = Field(..., description="Service name from SERVICE_CATALOGUE")
    user_id: int | None = Field(None, description="Optional — for audit logging")
    auto_start: bool = Field(
        True,
        description=(
            "If true, the orchestrator starts the service in the background "
            "when the session opens. Set False for sessions where you just "
            "want to record interest without spinning anything up."
        ),
    )


@router.post("", status_code=201)
async def open_session(req: SessionOpenRequest) -> dict[str, object]:
    """Open a session against a service. Auto-starts the service by default.

    Returns the session token the client must use for subsequent checkins
    and the eventual DELETE.
    """
    if req.service not in config.SERVICE_CATALOGUE:
        raise HTTPException(404, f"unknown service: {req.service}")

    token = uuid4()
    await db.execute(
        """
        INSERT INTO platform.service_sessions
            (service_name, user_id, token, opened_at, last_seen_at)
        VALUES ($1, $2, $3, now(), now())
        """,
        req.service, req.user_id, token,
    )
    await audit.write(
        "session_opened",
        service_name=req.service, user_id=req.user_id,
        details={"token": str(token), "auto_start": req.auto_start},
    )

    started = False
    if req.auto_start:
        result = await docker_ops.start_service(req.service)
        started = result.ok
        await audit.write(
            "session_autostart" if result.ok else "session_autostart_failed",
            service_name=req.service,
            details={"returncode": result.returncode, "stderr": result.short_stderr},
        )

    return {"token": str(token), "service": req.service, "started": started}


@router.post("/{token}/checkin")
async def checkin(token: UUID) -> dict[str, object]:
    """Refresh last_seen_at for an open session. Idempotent.

    No-op if the session doesn't exist — we don't 404 because that would
    spam logs in the normal case of a session that was just deleted but
    the client's next checkin is already in flight.
    """
    result = await db.execute(
        "UPDATE platform.service_sessions SET last_seen_at = now() WHERE token = $1",
        token,
    )
    # asyncpg's execute returns 'UPDATE n' — n>0 means we hit a row.
    return {"ok": True, "matched": result.endswith("0") is False}


@router.delete("/{token}", status_code=204)
async def close_session(token: UUID) -> None:
    """Close a session. The reconciler will eventually shut the service down
    if no other sessions are open and it's not pinned."""
    row = await db.fetchrow(
        "DELETE FROM platform.service_sessions WHERE token = $1 RETURNING service_name, user_id",
        token,
    )
    if row is not None:
        await audit.write(
            "session_closed",
            service_name=row["service_name"], user_id=row["user_id"],
            details={"token": str(token)},
        )
